### ISSUE TITLE
Spaces between characters in kernel options

### ISSUE THREAD

**Issue by mmstick** [pop-os/kernelstub#20]
Seems the latest version of kernelstub has an issue with the way it is parsing arguments. Unsure on the cause at the moment, but each character in a word is getting a space between it. Currently looking into it.

@isantop

**Comment by isantop** [comment]
Is there some example output of what is actually happening?

**Comment by mmstick** [comment]
Noticed this in my efi loader entry:

```
options root=UUID=1343343e-9802-43da-9a17-0ac176416566 ro q u i e t   l o g l e v e l = 0
```

Similar happens with a fresh install using the latest debug ISO, where `quiet loglevel=0 systemd.show_status=false splash` gets expanded in a similar fashion.

**Comment by brs17** [comment]
Is what is shown in the installer logs (of the debug ISO) and similarly in the config file. ```WARN: Kernel Boot Options:.q u i e t   l o g l e v e l = 0   s y s t e m d . s h o w _ s t a t u s = f a l s e   s p l a s h```
