### ISSUE TITLE
Can't install the new Linux kernel and new initramfs?

### ISSUE THREAD

**Issue by XtremeMusic2** [pop-os/kernelstub#69]
**Distribution (run `cat /etc/os-release`):**
 
 NAME="Pop!_OS"
VERSION="22.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 22.04 LTS"
VERSION_ID="22.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=jammy
UBUNTU_CODENAME=jammy
LOGO=distributor-logo-pop-os

 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**
linux-image-6.0.6-76060006-generic:
  Installed: 6.0.6-76060006.202210290932~1669062050~22.04~d94609a
  Candidate: 6.0.6-76060006.202210290932~1669062050~22.04~d94609a
  Version table:
 *** 6.0.6-76060006.202210290932~1669062050~22.04~d94609a 1001
       1001 http://apt.pop-os.org/release jammy/main amd64 Packages
        100 /var/lib/dpkg/status

**Issue/Bug Description:**
For some reason, I cannot update the new Linux kernel. I have not had problems doing it before, but now this time, it errors out on me saying it cannot copy the Kernel to the ESP. I have tried some of the steps at the package manager issues page to no avail and the dev on Discord who tried fixing it sent me here to report it if that failed. Additionally, the laptop said I had nothing to boot from and so I had to go to the boot menu and launch the old kernel. I have no idea what went wrong so I'm reporting it here to see if someone will help me get this working or fix this bug.

**Steps to reproduce (if you know):**

Run sudo apt upgrade

**Expected behavior:**

Successfully compile and install the kernel and initramfs

**Other Notes:**
I am using a Dell XPS 7590.
Here are the logs from when I ran sudo apt upgrade -f.

`
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
0 upgraded, 0 newly installed, 0 to remove and 20 not upgraded.
2 not fully installed or removed.
After this operation, 0 B of additional disk space will be used.
Setting up linux-image-6.0.6-76060006-generic (6.0.6-76060006.202210290932~1669062050~22.04~d94609a) ...
Setting up initramfs-tools (0.140ubuntu13) ...
update-initramfs: deferring update (trigger activated)
Processing triggers for linux-image-6.0.6-76060006-generic (6.0.6-76060006.202210290932~1669062050~22.04~d94609a) ...
/etc/kernel/postinst.d/dkms:
 * dkms: running auto installation service for kernel 6.0.6-76060006-generic
Error! The /var/lib/dkms/wireguard/1.0.20210606/6.0.6-76060006-generic/x86_64/dkms.conf for module wireguard includes a BUILD_EXCLUSIVE directive which does not
 match this kernel/arch.
This indicates that it should not be built.
   ...done.
/etc/kernel/postinst.d/initramfs-tools:
update-initramfs: Generating /boot/initrd.img-6.0.6-76060006-generic
cryptsetup: WARNING: Resume target cryptswap uses a key file
kernelstub.Config    : INFO     Looking for configuration...
kernelstub           : INFO     System information: 

    OS:..................Pop!_OS 22.04
    Root partition:....../dev/dm-1
    Root FS UUID:........eb92492b-ba9f-476f-a91b-57e33582ae33
    ESP Path:............/boot/efi
    ESP Partition:......./dev/nvme0n1p1
    ESP Partition #:.....1
    NVRAM entry #:.......-1
    Boot Variable #:.....0000
    Kernel Boot Options:.quiet loglevel=0 systemd.show_status=false splash
    Kernel Image Path:.../boot/vmlinuz-6.0.6-76060006-generic
    Initrd Image Path:.../boot/initrd.img-6.0.6-76060006-generic
    Force-overwrite:.....False

kernelstub.Installer : INFO     Copying Kernel into ESP
kernelstub.Installer : ERROR    Couldn't copy the kernel onto the ESP!
This is a critical error and we cannot continue. Check your settings to see if t
here is a typo. Otherwise, check permissions and try again.
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/kernelstub/installer.py", line 271, in co
py_files
    shutil.copy(src, dest)
  File "/usr/lib/python3.10/shutil.py", line 417, in copy
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/usr/lib/python3.10/shutil.py", line 256, in copyfile
    with open(dst, 'wb') as fdst:
OSError: [Errno 30] Read-only file system: '/boot/efi/EFI/Pop_OS-eb92492b-ba9f-4
76f-a91b-57e33582ae33/vmlinuz.efi'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/kernelstub/installer.py", line 128, in se
tup_kernel
    self.copy_files(
  File "/usr/lib/python3/dist-packages/kernelstub/installer.py", line 275, in co
py_files
    raise FileOpsError("Could not copy one or more files.")
kernelstub.installer.FileOpsError: Could not copy one or more files.
run-parts: /etc/initramfs/post-update.d//zz-kernelstub exited with return code 1
70
run-parts: /etc/kernel/postinst.d/initramfs-tools exited with return code 1
dpkg: error processing package linux-image-6.0.6-76060006-generic (--configure):
 installed linux-image-6.0.6-76060006-generic package post-installation script s
ubprocess returned error exit status 1
Processing triggers for initramfs-tools (0.140ubuntu13) ...
update-initramfs: Generating /boot/initrd.img-6.0.6-76060006-generic
cryptsetup: WARNING: Resume target cryptswap uses a key file
kernelstub.Config    : INFO     Looking for configuration...
kernelstub           : INFO     System information: 

    OS:..................Pop!_OS 22.04
    Root partition:....../dev/dm-1
    Root FS UUID:........eb92492b-ba9f-476f-a91b-57e33582ae33
    ESP Path:............/boot/efi
    ESP Partition:......./dev/nvme0n1p1
    ESP Partition #:.....1
    NVRAM entry #:.......-1
    Boot Variable #:.....0000
    Kernel Boot Options:.quiet loglevel=0 systemd.show_status=false splash
    Kernel Image Path:.../boot/vmlinuz-6.0.6-76060006-generic
    Initrd Image Path:.../boot/initrd.img-6.0.6-76060006-generic
    Force-overwrite:.....False

kernelstub.Installer : INFO     Copying Kernel into ESP
kernelstub.Installer : ERROR    Couldn't copy the kernel onto the ESP!
This is a critical error and we cannot continue. Check your settings to see if t
here is a typo. Otherwise, check permissions and try again.
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/kernelstub/installer.py", line 271, in co
py_files
    shutil.copy(src, dest)
  File "/usr/lib/python3.10/shutil.py", line 417, in copy
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/usr/lib/python3.10/shutil.py", line 256, in copyfile
    with open(dst, 'wb') as fdst:
OSError: [Errno 30] Read-only file system: '/boot/efi/EFI/Pop_OS-eb92492b-ba9f-4
76f-a91b-57e33582ae33/vmlinuz.efi'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/kernelstub/installer.py", line 128, in se
tup_kernel
    self.copy_files(
  File "/usr/lib/python3/dist-packages/kernelstub/installer.py", line 275, in co
py_files
    raise FileOpsError("Could not copy one or more files.")
kernelstub.installer.FileOpsError: Could not copy one or more files.
run-parts: /etc/initramfs/post-update.d//zz-kernelstub exited with return code 1
70
dpkg: error processing package initramfs-tools (--configure):
 installed initramfs-tools package post-installation script subprocess returned 
error exit status 1
Errors were encountered while processing:
 linux-image-6.0.6-76060006-generic
 initramfs-tools
E: Sub-process /usr/bin/dpkg returned an error code (1)
`

**Comment by XtremeMusic2** [comment]
screwed up the formatting and github will not let me delete this, edit button also made me submit my edit as a new issue

**Comment by mmstick** [comment]
> OSError: [Errno 30] Read-only file system: '/boot/efi/EFI/Pop_OS-eb92492b-ba9f-4
76f-a91b-57e33582ae33/vmlinuz.efi'

You need to find out why your EFI partition is read-only. Filesystem corruption most likely.

**Comment by XtremeMusic2** [comment]
solved it, all i had to do was unmount the efi partition, type `sudo fsck -n -f /boot/efi`, and it worked, i got the new linux kernel to install
