### ISSUE TITLE
Can't run kernelstub as root

### ISSUE THREAD

**Issue by Logilype** [pop-os/kernelstub#71]
**Distribution (run `cat /etc/os-release`):**
 Pop!_OS 22.04 LTS
 
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**
kernelstub

**Issue/Bug Description:**
If I try to run "sudo kernelstub", I get this:
> Traceback (most recent call last):
>   File "/usr/bin/kernelstub", line 244, in <module>
>     main()
>   File "/usr/bin/kernelstub", line 241, in main
>     kernelstub.main(args)
>   File "/usr/lib/python3/dist-packages/kernelstub/application.py", line 142, in main
>     config = Config.Config()
>   File "/usr/lib/python3/dist-packages/kernelstub/config.py", line 50, in __init__
>     self.config = self.load_config()
>   File "/usr/lib/python3/dist-packages/kernelstub/config.py", line 60, in load_config
>     self.config = json.load(config_file)
>   File "/usr/lib/python3.10/json/__init__.py", line 293, in load
>     return loads(fp.read(),
>   File "/usr/lib/python3.10/json/__init__.py", line 346, in loads
>     return _default_decoder.decode(s)
>   File "/usr/lib/python3.10/json/decoder.py", line 337, in decode
>     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
>   File "/usr/lib/python3.10/json/decoder.py", line 353, in raw_decode
>     obj, end = self.scan_once(s, idx)
> json.decoder.JSONDecodeError: Expecting ',' delimiter: line 6 column 7 (char 77)

**Steps to reproduce (if you know):**

**Expected behavior:**
To show the help page or to say use --help or something?

**Other Notes:**

**Comment by isantop** [comment]
What are the contents of your `/etc/kernelstub/configuration` file? It looks like something has corrupted that file which is now preventing it from loading correctly.

**Comment by Logilype** [comment]
> What are the contents of your `/etc/kernelstub/configuration` file? It looks like something has corrupted that file which is now preventing it from loading correctly.

Actually it was me who configured the file wrong
